cloud:
  aws:
    credentials:
      access-key: AKIAXSORP2DCPV3ZW2M6
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: emarketstorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
